name: goldboot-action
description: Build goldboot images with CI
author: Tyler Cook

inputs:
  output:
    description: The destination image path (relative to the CI workspace)
    required: true
    default: image.gb
  context:
    description: The directory path containing a goldboot config (relative to the CI workspace)
    required: true
    default: .
  log-level:
    description: Set the logging level
    required: true
    default: info

runs:
  using: docker
  image: Dockerfile
  env:
    OUTPUT: /github/workspace/${{ inputs.output }}
    CONTEXT: /github/workspace/${{ inputs.context }}
    RUST_LOG: ${{ inputs.log-level }}
