name: goldboot-action
description: Build goldboot images with CI
author: Tyler Cook

inputs:
  output:
    description: The destination image path
    required: true
    default: image.gb

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_OUTPUT_FILE: /github/workspace/${{ inputs.output }}
